basechart:
  replicaCount: 

  image:
    repository: 
    tag: ""
    pullPolicy: Always
    imagePullSecrets: []

  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    create: 
    automount: 
    annotations: {}
    name: ""

  podAnnotations: {}
  podLabels:
    tier: 

  podSecurityContext:
    runAsUser: 

  securityContext:
    runAsNonRoot: 
    readOnlyRootFilesystem: 
    allowPrivilegeEscalation: 
    capabilities:
      drop:
        - ALL

  deployment:
    containerPort: 

  volumeMounts: []
    
  volumes: []
  service:
    type: ClusterIP
    port: 
    targetPort: 
    annotations: {}

  ingress:
    enabled: 
    className: 
    annotations:
      kubernetes.io/ingress.class: 
    hosts:
      - host: 
        paths:
          - path: 
            pathType: Prefix
    tls: []

  livenessProbe:
    httpGet:
      path: 
      port: 
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  readinessProbe:
    httpGet:
      path: 
      port: 
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

  resources:
    requests:
      cpu: 
      memory: 
    limits:
      cpu: 
      memory: 

  autoscaling:
    enabled: 
    minReplicas: 
    maxReplicas: 
    targetCPUUtilizationPercentage: 
    targetMemoryUtilizationPercentage: 

  nodeSelector: {}
  tolerations: []
  affinity: {}

