basechart:
  replicaCount: 1

  image:
    repository: 
    tag: ""
    pullPolicy: Always
    imagePullSecrets: []

  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""

  podAnnotations: {}
  podLabels:
    tier: be

  podSecurityContext:
    runAsUser: 101

  securityContext:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

  deployment:
    containerPort: 3090

  volumeMounts: []
    
  volumes: []
  service:
    type: ClusterIP
    port: 
    targetPort: 
    annotations: {}

  ingress:
    enabled: false
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: demo-app.local
        paths:
          - path: /demo-test
            pathType: Prefix
    tls: []

  livenessProbe:
    httpGet:
      path: /health
      port: 
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  readinessProbe:
    httpGet:
      path: /health
      port: 
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 512Mi

  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}
  tolerations: []
  affinity: {}

