{{- if .Values.basechart.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "basechart.serviceAccountName" . }}
  labels:
    {{- include "basechart.labels" . | nindent 4 }}
  {{- with .Values.basechart.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.basechart.serviceAccount.automount }}
{{- end }}